# Generated by Django 2.0.2 on 2019-01-02 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OH_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Project', max_length=100)),
                ('description', models.TextField()),
                ('year_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('year_published', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(upload_to='')),
                ('domain', models.CharField(choices=[('Big Data', 'Big Data'), ('Cloud Computing', 'Cloud Computing'), ('Computer Vision & Artificial Intelligence', 'Computer Vision & Artificial Intelligence'), ('Data Mining & Analytics', 'Data Mining & Analytics'), ('Image Processing/Computer Vision', 'Image Processing/Computer Vision'), ('Internet of Things(IOT)', 'Internet of Things(IOT)'), ('Machine Learning', 'Machine Learning'), ('Mobile Computing', 'Mobile Computing'), ('Natural Language Processing/Artificial Intelligence', 'Natural Language Processing/Artificial Intelligence'), ('Networking/Security', 'Networking/Security'), ('none', 'none')], default='none', max_length=100)),
                ('company', models.CharField(default='none', max_length=100)),
                ('supervisor', models.CharField(default='none', max_length=100)),
                ('contributers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='oh_project',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='BEProjectsApp.Teacher'),
        ),
    ]
