export const Domains = [
    "Data Mining & Analytics",
    "Machine Learning",
    "Deep Learning",
    "Image Processing/Computer Vision",
    "Natural Language Processing/Artificial Intelligence",,
    "Networking/Security",
    "Internet of ThingsIOT",
    "Mobile Computing",
    "Big Data",
    "Cloud Computing",
    "Computer Vision & Artificial Intelligence",
    "Blockchain",
    "Operating Systems",
    "GAN's",
    "Audio Processing",
    "Video Processing",
    "Cryptography",
]