# Generated by Django 2.1.4 on 2019-01-07 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inhouse_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('year_published', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(upload_to='')),
                ('approved', models.BooleanField(default=False)),
                ('contributers', models.TextField()),
                ('domain', models.CharField(choices=[(1, 'Data Mining & Analytics'), (2, 'Machine Learning'), (3, 'Deep Learning'), (4, 'Image Processing/Computer Vision'), (5, 'Natural Language Processing/Artificial Intelligence'), (6, 'Networking/Security'), (7, 'Internet of Things(IOT)'), (8, 'Mobile Computing'), (9, 'Big Data'), (10, 'Cloud Computing'), (11, 'Computer Vision & Artificial Intelligence'), (12, 'Blockchain')], default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='inhouse_project',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='BEProjectsApp.Teacher'),
        ),
    ]
